### ISSUE TITLE
missing SmartRoadSense.Core

### ISSUE THREAD

**Issue by MarcoSal** [SmartRoadSense/client-apps#27]
Hi,
when I open the project in VS2017, I can not find 'SmartRoadSense.Core'. It does not seem to be included in the package ...

**Comment by MarcoSal** [comment]
ok..Thanks

**Comment by MarcoSal** [comment]
news about SmartRoadSense.Core?

**Comment by bsor-dev** [comment]
@LorenzCK still not available or it is included at client-app? Is it the sensorpack.cs?

**Comment by LorenzCK** [comment]
Hi @MarcoSal and @rosnaib11 ,
SmartRoadSense at the moment is maintained/owned by a private company (Digit SRL) and, for the time being, the core algorithm will not released under an open source license. It will remain unavailable for now on GitHub.
If you want to propose pilot projects or other custom experiments with SmartRoadSense, I would urge you to [take contact with the company](https://digit.srl/contatti/). Thanks!
